# How to launch a container with a PostgreSQL database using Docker Compose

version: '3.8'
services:
  db:
    image: postgres:15-alpine # Использовать облегченную версию
    container_name: memorizy_db
    ports:
      - "127.0.0.1:5432:5432"
    environment:  # Настройки Базы Данных при первом запуске
      POSTGRES_DB: ${DB_NAME:-memorizy_db}
      POSTGRES_USER: ${DB_USER:-memorizy_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Set DB_PASSWORD in .env}
    volumes:  # Связывание директории с данными и именованный том на хост-машине
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  # Объявление именованного тома в корне файла