# Basic settings that the server needs to work with

spring.application.name=memorizy-server
spring.config.import=optional:file:.env[.properties]
server.address=${SERVER_ADDRESS:0.0.0.0}
server.port=${SERVER_PORT:8080}

# Data Base Connection settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/memorizy_db}
spring.datasource.username=${DB_USER:memorizy_user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings - send queries to DB using objects instead of using SQL queries
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Extra secret key for token and his expiration time
application.security.jwt.secret=${JWT_SECRET}
application.security.jwt.expiration=${JWT_EXPIRATION_MS:7776000000}